sudo:
  required

services:
  - docker

language: java

jdk:
  - oraclejdk8

install: gradle -p product-management/webservice assemble & gradle -p user-management/webservice assemble & gradle -p eureka assemble

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - master

after_success:

   #LOGIN
  - docker login -u $D_USER -p $D_PASS

   #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

   #PRODUCT MANAGEMENT
  - export PRODUCT_MANAGEMENT=vadimeladii7/spring-boot2-microservice-product-management
  - docker build -t $PRODUCT_MANAGEMENT:$COMMIT ./product-management
  - docker tag $PRODUCT_MANAGEMENT:$COMMIT $PRODUCT_MANAGEMENT:$TAG
  - docker push $PRODUCT_MANAGEMENT

   #USER MANAGEMENT
  - export USER_MANAGEMENT=vadimeladii7/spring-boot2-microservice-user-management
  - docker build -t $USER_MANAGEMENT:$COMMIT ./user-management
  - docker tag $USER_MANAGEMENT:$COMMIT $USER_MANAGEMENT:$TAG
  - docker push $USER_MANAGEMENT

   #EUREKA
  - export EUREKA=vadimeladii7/spring-boot2-microservice-eureka
  - docker build -t $EUREKA:$COMMIT ./eureka
  - docker tag $EUREKA:$COMMIT $EUREKA:$TAG
  - docker push $EUREKA