version: '2'
services:

# EUREKA APPLICATION
    eureka-app:
        image: vadimeladii7/spring-boot2-microservice-eureka:latest
        ports:
        - 8761:8761
        environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/
        - SERVER_PORT=8761

# ZUUL APPLICATION
    zuul-app:
        image: vadimeladii7/spring-boot2-microservice-zuul:latest
        ports:
        - 8762:8762
        links:
        - eureka-app
        depends_on:
        - eureka-app
        environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/
        - SERVER_PORT=8762

# POSTGRES PRODUCT
    db-product:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres

# PRODUCT MANAGEMENT APPLICATION
    product-management:
        image: vadimeladii7/spring-boot2-microservice-product-management:latest
        ports:
            - 8082:8082
        links:
            - db-product
            - eureka-app
        depends_on:
            - db-product
            - eureka-app
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db-product:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_FLYWAY_URL=jdbc:postgresql://db-product:5432/postgres
            - SPRING_FLYWAY_USER=postgres
            - SPRING_FLYWAY_PASSWORD=postgres
            - SERVER_PORT=8082
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/

    # POSTGRES USER
    db-user:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres

# USER MANAGEMENT APPLICATION
    user-management:
        image: vadimeladii7/spring-boot2-microservice-user-management:latest
        ports:
        - 8081:8081
        links:
        - db-user
        - eureka-app
        depends_on:
        - db-user
        - eureka-app
        environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db-user:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_FLYWAY_URL=jdbc:postgresql://db-user:5432/postgres
        - SPRING_FLYWAY_USER=postgres
        - SPRING_FLYWAY_PASSWORD=postgres
        - SERVER_PORT=8081
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/

# USER MANAGEMENT2 APPLICATION
    user-management2:
        image: vadimeladii7/spring-boot2-microservice-user-management:latest
        ports:
        - 8091:8091
        links:
        - db-user
        - eureka-app
        depends_on:
        - db-user
        - eureka-app
        environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db-user:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_FLYWAY_URL=jdbc:postgresql://db-user:5432/postgres
        - SPRING_FLYWAY_USER=postgres
        - SPRING_FLYWAY_PASSWORD=postgres
        - SERVER_PORT=8091
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/

# TRACKING MANAGEMENT APPLICATION
    tracking-management:
        image: vadimeladii7/spring-boot2-microservice-tracking-management:latest
        ports:
        - 8083:8083
        links:
        - eureka-app
        depends_on:
        - eureka-app
        environment:
        - SERVER_PORT=8083
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/

# GEOLOCATION MANAGEMENT APPLICATION
    geolocation-management:
        image: vadimeladii7/spring-boot2-microservice-geolocation-management:latest
        ports:
        - 8084:8084
        links:
        - eureka-app
        depends_on:
        - eureka-app
        environment:
        - SERVER_PORT=8084
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-app:8761/eureka/
