spring:
  # Spring configuration
  main:
    allow-bean-definition-overriding: true

# Server configuration
server:
  port: 8083

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/