spring:
  # Spring configuration
  main:
    allow-bean-definition-overriding: true

  # Flyway Sql Migration
  flyway:
    url: jdbc:postgresql://localhost:5432/user-management
    user: postgres
    password: postgres

  # Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://localhost:5432/user-management
    username: postgres
    password: postgres
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server configuration
server:
  port: 8081

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/